export const data = [
    {
        id: 1,
        description: 'Villa Jane will astonish every guest with its breathtaking views',
        price: 2000,
        location: 'Aspen',
        bedroom: '05',
        totalArea: 7600,
        detailsDescription: 'A chalet-style Aspen home that combines privacy with in-town',
        image: require("../assets/images/villas/001_villa.jpg"), 
    },
    {
        id: 2, 
        description: 'An ultra-exclusive mountain home Ranch-inspired luxury living',
        price: 3500,
        location: 'Aspen',
        bedroom: '05',
        totalArea: 7400,
        detailsDescription: 'A chalet-style Aspen home that combines privacy with in-town',
        image: require("../assets/images/villas/002_villa.jpg"), 
     },
     {
        id: 3, 
        description: 'A luxurious villa in the nature',
        price: 10900,
        location: 'Tskaltubo',
        bedroom: '07',
        totalArea: 5400,
        detailsDescription: 'A chalet-style home in the Green City',
        image: require("../assets/images/villas/003_villa.jpg"), 
     },
     {
        id: 4, 
        description: 'Warm and calm villa at Bakuriani Resort',
        price: 8700,
        location: 'Bakuriani',
        bedroom: '03',
        totalArea: 3400,
        detailsDescription: 'A chalet-style Aspen home that combines privacy with in-town',
        image: require("../assets/images/villas/004_villa.jpg"),
     },
     {
        id: 5, 
        description: 'Sunny and luxurious villa near the Black Sea, Georgia',
        price: 4590,
        location: 'Kobuleti',
        bedroom: '05',
        totalArea: 3970,
        detailsDescription: 'A chalet-style Aspen home that combines privacy with in-town',
        image: require("../assets/images/villas/005_villa.jpg"), 
     },
     {
        id: 6, 
        description: 'Spend sunny days at beautiful villa at Batumi',
        price: 12000,
        location: 'Batumi',
        bedroom: '10',
        totalArea: 13000,
        detailsDescription: 'A chalet-style Aspen home that combines privacy with in-town',
        image: require("../assets/images/villas/006_villa.jpg"), 
     },
     {
        id: 7, 
        description: 'Villa in the City of Hug',
        price: 10000,
        location: 'Kutaisi',
        bedroom: '12',
        totalArea: 9850,
        detailsDescription: 'A luxurious and astonishing villa in the Father-City of Georgia',
        image: require("../assets/images/villas/007_villa.jpg"), 
     },
     {
        id: 8, 
        description: 'Villa in Gori',
        price: 2000,
        location: 'Gori',
        bedroom: '02',
        totalArea: 1400,
        detailsDescription: 'Spend hot days in the astonishing villa near the home of Soso',
        image: require("../assets/images/villas/008_villa.jpg"), 
     },
     {
        id: 9, 
        description: 'Villa in California',
        price: 20000,
        location: 'Los Angeles',
        bedroom: '14',
        totalArea: 10170,
        detailsDescription: 'A chalet-style Aspen home that combines privacy with in-town',
        image: require("../assets/images/villas/009_villa.jpg"), 
     },
     {
        id: 10, 
        description: 'Vila "White House" in Kutaisi',
        price: 13000,
        location: 'Kutaia',
        bedroom: '9',
        totalArea: 8900,
        detailsDescription: '"Katkata" and luxurious villa in the City of Chamomiles',
        image: require("../assets/images/villas/010_villa.jpg"), 
     }
]