export const data = [
    {
        id: 1,
        description: 'Villa Jane will astonish every guest with its breathtaking views',
        price: 2000,
        location: 'Aspen',
        badroom: '05',
        totalArea: '7,600',
        detailsDescription: 'A chalet-style Aspen home that combines privacy with in-town',
        image: require("./images/001_villa.jpg"), 
    },
    {
        id: 2, 
        description: 'An ultra-exclusive mountain home Ranch-inspired luxury living',
        price: 3500,
        location: 'Aspen',
        badroom: '05',
        totalArea: '7,400',
        detailsDescription: 'A chalet-style Aspen home that combines privacy with in-town',
        image: require("./images/002_villa.jpg"), 
     },
     {
        id: 3, 
        description: 'A luxurious villa in the nature',
        price: 10900,
        location: 'Tskaltubo',
        badroom: '07',
        totalArea: '5,400',
        detailsDescription: 'A chalet-style home in the Green City',
        image: require("./images/003_villa.jpg"), 
     },
     {
        id: 4, 
        description: 'Warm and calm villa at Bakuriani Resort',
        price: 8700,
        location: 'Bakuriani',
        badroom: '03',
        totalArea: '3,400',
        detailsDescription: 'A chalet-style Aspen home that combines privacy with in-town',
        image: require("./images/004_villa.jpg"),
     },
     {
        id: 5, 
        description: 'Sunny and luxurious villa near the Black Sea, Georgia',
        price: 4590,
        location: 'Kobuleti',
        badroom: '05',
        totalArea: '3,970',
        detailsDescription: 'A chalet-style Aspen home that combines privacy with in-town',
        image: require("./images/005_villa.jpg"), 
     },
     {
        id: 6, 
        description: 'Spend sunny days at beautiful villa at Batumi',
        price: 12000,
        location: 'Batumi',
        badroom: '10',
        totalArea: '13,000',
        detailsDescription: 'A chalet-style Aspen home that combines privacy with in-town',
        image: require("./images/006_villa.jpg"), 
     },
     {
        id: 7, 
        description: 'Villa in the City of Hug',
        price: 10000,
        location: 'Kutaisi',
        badroom: '12',
        totalArea: '9,850',
        detailsDescription: 'A luxurious and astonishing villa in the Father-City of Georgia',
        image: require("./images/007_villa.jpg"), 
     },
     {
        id: 8, 
        description: 'Villa in Gori',
        price: 2000,
        location: 'Gori',
        badroom: '02',
        totalArea: '1,400',
        detailsDescription: 'Spend hot days in the astonishing villa near the home of Soso',
        image: require("./images/008_villa.jpg"), 
     },
     {
        id: 9, 
        description: 'Villa in California',
        price: 20000,
        location: 'Los Angeles',
        badroom: '14',
        totalArea: '10,170',
        detailsDescription: 'A chalet-style Aspen home that combines privacy with in-town',
        image: require("./images/009_villa.jpg"), 
     },
     {
        id: 10, 
        description: 'Vila "White House" in Kutaisi',
        price: 13000,
        location: 'Kutaia',
        badroom: '9',
        totalArea: '8,900',
        detailsDescription: '"Katkata" and luxurious villa in the City of Chamomiles',
        image: require("./images/010_villa.jpg"), 
     }
]